name: build kernel

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  MANIFEST_BRANCH: twrp-11
  DEVICE: RMX2151
  DT_LINK: https://github.com/Gofaraway71/twrp_realme_RMX2151
  DT_PATH: device/realme/RMX2151
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initializing environment
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        docker rmi `docker images -q`
        curl https://raw.githubusercontent.com/snjy4/TWRP_BUILD/main/cleanup.sh | bash
        sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
        git config --global user.name "Gofaraway71"
        git config --global user.email "abdou.bens34000@gmail.com"
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get clean
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison aria2
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo
    - name: Build
      run: |
       git config --global user.name "Gofaraway71"
       git config --global user.email "aalbatron@gmail.com"
       git clone https://github.com/rama982/clang "$HOME/clang" --depth=1 >/dev/null
       git clone https://github.com/osm0sis/AnyKernel3 "$HOME/anykernel" --depth=1
       sed -i -e 's/devicecheck=1/devicecheck=0/' -e '/block/d' "$HOME/anykernel/anykernel.sh"
       mkdir "$HOME/kernel"
       cd "$HOME/kernel"
       git init >/dev/null
       git fetch https://github.com/realme-mt6785-devs/android_kernel_realme_mt6785 "$HEAD" --depth=1
       git reset --hard FETCH_HEAD >/dev/null
       export PATH="$HOME/clang/bin:$PATH"
       export ARCH=arm64
       export KBUILD_BUILD_USER="Gofaraway71"
       make RM6785_defconfig O="$HOME/out"
       make -j "$(nproc --all)" O="$HOME/out" CC="clang" \
       LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip \
       CROSS_COMPILE=aarch64-linux-gnu-
       KERNEL_IMAGE="$HOME/out/arch/arm64/boot/Image.gz"
       if ! [ -e "$KERNEL_IMAGE" ]; then exit; fi
       cp -v "$KERNEL_IMAGE" "$HOME/anykernel"
       cd "$HOME/anykernel"
       ZIPNAME="RM6785-kernel-ci-$(date -u +%Y%m%d_%H%M).zip"
       zip -r "$ZIPNAME" *
       curl -T "$ZIPNAME" https://free.keep.sh
